config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resources :registrations, only: %i[new create]
  resources :sessions, only: %i[new create destroy]

  get '/signup', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  delete '/sign_out', to: 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#omniauth'
  post '/auth/:provider/callback' => 'sessions#omniauth'
  get '/dashboard', to: 'dashboard#show'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates_uniqueness_of :email
  has_secure_password

  def self.from_registration(user_params)
    #    if user_params[:email] != ""
    User.find_or_create_by!(email: user_params[:email].downcase) do |u|
      u.uid = (User.maximum(:id) || 0) + 1
      u.provider = 'email_oath'
      u.first_name = user_params[:first_name]
      u.last_name = user_params[:last_name]
      u.email = user_params[:email]
      u.encrypted_password = user_params[:password]
      u.password_digest = BCrypt::Password.create(user_params[:password])
    end
    #    else
    #      User.new
    #    end
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    User.find_or_create_by!(provider: access_token.provider, uid: access_token.uid) do |u|
      u.uid = access_token.uid
      u.provider = access_token.provider

      if data.name
        u.first_name = data.name.split.first
        u.last_name = data.name.split.last

      else
        u.first_name = data.first_name
        u.last_name = data.last_name
      end

      u.email = data.email
      u.encrypted_password = SecureRandom.hex(15)
      u.password_digest = access_token.provider
    end
  end
end

app/models/user_account.rb
# frozen_string_literal: true

class UserAccount < ApplicationRecord
  belongs_to :user_login_details
end

app/models/user_login_datum.rb
# frozen_string_literal: true

class UserLoginDatum < ApplicationRecord
  has_one :user_account
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :user_signed_in?
  # before_action :authenticate_user

  def current_user
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end

  def authenticate_user
    redirect_to new_session_path, flash: { danger: 'You must be signed in' } if current_user.nil?
  end

  def redirect_if_authenticated
    redirect_to dashboard_path, flash: { info: 'You are already logged in.' } if user_signed_in?
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def show; end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @github_client_id = ENV['GITHUB_CLIENT_ID']
    @google_client_id = ENV['GOOGLE_CLIENT_ID']
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

# app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  rescue_from ActiveRecord::RecordInvalid, with: :record_invalid
  #    skip_before_action :authenticate_user, only: [:new, :create]
  before_action :redirect_if_authenticated, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    #      @user = User.new(user_params)
    @user = User.find_by_email(user_params[:email].downcase)
    if !@user.nil? && @user.valid?
      redirect_to root_path, flash: { alert: 'Account already exists' }
    else
      @user = User.from_registration(user_params)
      if !@user.nil? && @user.valid?
        session[:user_id] = @user.id
        redirect_to root_path, flash: { success: 'Registration successful' }
      else
        @user = User.new(user_params)
        redirect_to new_registration_path, flash: { failure: 'Invalid input' }
      end
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def record_invalid(_exception)
    redirect_to new_registration_path, flash: { failure: 'Invalid Email or Password' }
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :not_found_response
  #   skip_before_action :authenticate_user, only: [:new, :create]
  #   before_action :redirect_if_authenticated, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email!(user_params[:email].downcase)

    if @user.present?
      if @user.provider == 'google_oauth2'
        redirect_to root_path, flash: { failure: 'Google sign in found please use Google' }
        return
      end

      if @user.present? && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to dashboard_path, flash: { success: 'Logged in successfully' }
        return
      end

      if @user.present? && !@user.authenticate(params[:user][:password])
        redirect_to new_session_path, flash: { failure: 'Invaild Email / Password Please try again' }
        nil
      end

    else
      redirect_to new_session_path, flash: { failure: 'Invaild Email / Password Please try again' }
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: { success: 'Logged Out' }
  end

  def omniauth
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to dashboard_path, flash: { success: 'Logged in successfully' }
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

  private

  def not_found_response(_exception)
    redirect_to new_session_path, flash: { failure: 'Invaild Email / Password Please try again' }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/registrations_helper.rb
# frozen_string_literal: true

module RegistrationsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/dashboard/show.html.erb
<% if current_user %>
<h1>Welcome, <%= current_user.first_name %>  to MyMeds</h1>
<p> Email: <%= current_user.email %> </p>
<p> Login Provider: <%= current_user.provider %> </p>
<p> Id: <%= current_user.id %> </p>
<p> Uid: <%= current_user.uid %> </p>
<p> First Name: <%= current_user.first_name %> </p>

<h2> Your Meds </h2>
<% else %>
<% controller.redirect_to root_path flash: {info: 'You must be signed in'} %>
<% end %>

app/views/home/index.html.erb
<section>
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
    <div class="w-full bg-cyan-900 rounded-lg shadow md:mt-0 sm:max-w-md xl:p-0">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">

        <h1 class="text-cyan-200 text-3xl text-center font-bold">
          Welcome to MyMeds!
        </h1>

        <div class="grid grid-cols-1 gap-2">

          <%= button_to "Sign in with email", "/sessions/new", class: "w-full ml-3 bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium  hover:bg-cyan-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", method: :get %>
          <%= button_to "Sign in with Github", "/auth/github", class: "w-full ml-3 bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium  hover:bg-cyan-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", data: { turbo: false } %>
          <%= button_to "Sign in with Google", '/auth/google_oauth2', class: "w-full ml-3 bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium hover:bg-cyan-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", method: :post, :data => { turbo: "false" } %>
          <%= button_to "Create an Account", "/registrations/new", class: "w-full ml-3 bg-cyan-700 py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-cyan-200 hover:bg-cyan-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", method: :get %>

        </div>
      </div>
    </div>
  </div>

</section>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mymeds</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="h-screen bg-gradient-to-b from-cyan-200 to-cyan-700 border-solid ">

    <nav class="bg-cyan-600 border-gray-200">
      <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="/dashboard" class="flex items-center space-x-3 rtl:space-x-reverse">
        <%= image_tag( 'MyMeds.png',style: 'display: block; margin: auto; width: 20%;')%>
        </a>

        <button data-collapse-toggle="navbar-dropdown" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-dropdown" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
        </button>
       <% if user_signed_in? %>
         <%= button_to "Sign Out", sign_out_path, class: "ml-3 bg-cyan-600 py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white hover:bg-cyan-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500",method: :delete %>
        <% end %>
      </div>
    </nav>

    <div class="max-w-6xl pt-4 mx-auto text-cyan-800" >
    <%= render 'layouts/flash' %>
    </div>


    <%= yield %>

  </body>
</html>